docs/rosa/byo-vpc/.gitignore
docs/rosa/byo-vpc/README.md
docs/rosa/byo-vpc/main.tf
docs/rosa/private-link/README.md

add TF byo-vpc

---

README.md
docs/rosa/sts/README.md

update base index and add single cluster advisory to sts doc

---

docs/ocp/common-images-namespace/README.md

add ocp public common images doc

---

docs/aws/waf/README.md
docs/aws/waf/alb.md
docs/aws/waf/cloud-front.md

fix waf docs

---

_layouts/default.html

remove source, fix github link

---

README.md
docs/aro/private-cluster.md

add private cluster instructions

---

docs/aro/egress-operator.md
docs/aro/private-cluster.md
docs/rosa/sts/README.md

egress operator - DO NOT MERGE

---

README.md
docs/aro/egress-operator.md
docs/aro/private-cluster.md

fix titles, add egress-ip to index

---

README.md
docs/aro/private-cluster.md

fix egress operator link

---

docs/rosa/sts/apply-roles.sh

update script to ensure json for aws commands that capture input

---

docs/aro/egress-ipam-operator.md
docs/aro/private-cluster.md

move LB actions to egress-ipam doc

---

docs/aro/disaster-recovery/README.md

update aro dr

---

docs/aro/disaster-recovery/README.md

more details for ARO DR

---

docs/o11y/az-log-analytics.md
docs/o11y/enable-monitoring.sh
docs/o11y/openshift-logging.md

Adding information in for setting up logs and metrics. The initial bit on OpenShift-Logging is probably ready for publication, but the bits on Azure need to be written out as steps instead of notes. This should be enough, though, for someone with experience to smooth out the edges and get up and running with the included basic OpenShift-Logging and/or shipping logs (and Prometheus metrics) to Azure Monitor.

[WIP] adds initial info on logs/metrics

---

docs/aws/waf/alb.md
docs/aws/waf/iam-policy.json
docs/aws/waf/values.yaml

update waf instructions to not require download

---

README.md
docs/demos/crane/README.md

add guide on crane

---

_config.yml

based on the variables in /_layouts/default.html I think this is what we need.

add google analytics id

---

docs/aro/clf-to-azure/README.md

add clusterlogging resource

---

docs/rosa/sts-with-private-link/README.md
docs/rosa/sts/README.md

rosa cli 1.1.0 changes

---

docs/rosa/sts-with-private-link/README.md
docs/rosa/sts/README.md

add task to configure service linked role for aws elb

---

docs/aro/clf-to-azure/README.md

Change query to reference openshift_CL

Correct Azure Portal Query

---

docs/aro/key-vault-csi/README.md

add aro key vault csi

---

README.md

add kv doc to site index

---

README.md
docs/rosa/aws-secrets-manager-csi/README.md

update markdown to remove frontmatter as its not working atm

---

README.md
docs/security/secrets-store-csi/README.md
docs/security/secrets-store-csi/hashicorp-vault.md
docs/security/secrets-store-csi/install-kubernetes-secret-store-driver.md
docs/security/secrets-store-csi/uninstall-kubernetes-secret-store-driver.md

add hashi csi

---

docs/rosa/aws-secrets-manager-csi/README.md

fix aws secrets csi doc formatting

---

docs/security/secrets-store-csi/hashicorp-vault.md
docs/security/secrets-store-csi/install-kubernetes-secret-store-driver.md
docs/security/secrets-store-csi/uninstall-kubernetes-secret-store-driver.md

do not use kube-system

---

docs/aro/clf-to-azure/README.md

fix clf azure heredocs

---

README.md
docs/aro/key-vault-csi/index.html
docs/security/secrets-store-csi/azure-key-vault.md

move aro key vault doc to security and use includes

---

docs/aro/ocm.md

It seems there isn't yet any public documentation that specifically calls out how to register ARO with OCM in a simple format. I felt it would be beneficial to have a quick guide that could be easily linked to and shared by other people. 
I hope that the docs are a reasonable enough quality - they're a bit rough and ready, but hopefully it should be enough to be a meaningful first commit :-) 
I didn't see a contributors checklist or similar, forgive me if I missed somewhere there!

Create docs for registering ARO with OCM, as I have not seen similar docs elsewhere

---

docs/rosa/custom-alertmanager/README.md

fix formatting for custom alertmanager

---

docs/rosa/federated-metrics-prometheus/README.md

update federated metrics doc to use helm

---

README.md
docs/rosa/sts-cluster-logging-addon/README.md

add clf addon workaround

---

README.md
docs/rosa/sts-cluster-logging-addon/README.md

update trust policy

---

.github/workflows/github-actions-lint.yaml
.github/workflows/github-actions-spellcheck.yaml
Makefile

the great spellcheck/lint fixer

---

.github/workflows/github-actions-lint.yaml
.github/workflows/github-actions-spellcheck.yaml
Makefile

Reverts rh-mobb/documentation#89

Revert "the great spellcheck/lint fixer"

---

docs/aro/egress-ipam-operator.md
docs/aro/private-cluster.md

fix private aro / egress-ip instructions

---

docs/rosa/aws-secrets-manager-csi/README.md
docs/security/secrets-store-csi/aws-provider-installer.yaml

update aws secrets csi to use safer path/ns

---

README.md
docs/rosa/federated-metrics/README.md
docs/rosa/federated-metrics/s3-policy.json

update metrics-to-s3 docs to use helm

---

docs/aro/clf-to-azure/README.md
docs/aro/federated-metrics/README.md
docs/aro/federated-metrics/thanos-grafana-operator.yaml

update aro federated metrics to use helm chart

---

.gitignore
README.md
_layouts/default.html
docs/aro/federated-metrics/README.md
docs/aro/federated-metrics/user-defined.md
docs/aro/private-cluster.md
docs/quickstart-aro.md
docs/quickstart-rosa.md
docs/rosa/federated-metrics/README.md
docs/rosa/federated-metrics/user-defined.md

Changing the disclaimer bar to be a warning box, updating the wording, and fixing Red Hat spelling.

Style and text changes

---

docs/rosa/private-link/README.md
docs/rosa/sts-with-private-link/README.md

Added mention about using valid subnets when BYOVPC to both ROSA private link and ROSA private link & sts docs.

Added: mention about using valid subnets

---

docs/rosa/sts-cluster-logging-addon/README.md

provide link to official workaround

---

docs/rosa/aws-efs-operator-on-rosa/README.md

add docs for aws efs operator on ROSA

---

README.md
docs/aro/egress-ipam-operator.md
docs/rosa/aws-efs-operator-on-rosa/README.md

fix formatting

---

docs/acm/observability/rosa/README.md

update acm obs to not use sts

---

docs/security/secrets-store-csi/install-kubernetes-secret-store-driver.md

update csi driver to lock k8s driver version

---

README.md
docs/rosa/aws-efs-csi-operator-sts/README.md

add efs csi operator

---

docs/aro/egress-ipam-operator.md

No longer need to remove the egress LB

update egress ipam operator to skip removing the egress LB

---

README.md
docs/aro/additional-ingress-controller/README.md

show adding aro additional ingress controller

---

docs/aro/additional-ingress-controller/README.md

fix domain variable

---

docs/aro/additional-ingress-controller/README.md

fix code indent blocks

---

docs/aro/private-cluster.md

update aro private for egress lockdown

---

docs/rosa/custom-alertmanager/README.md

fix code formatting

---

docs/aro/managed-upgrade-operator/README.md

add ARO managed upgrade operator instructions

---

README.md

update index for ECR / MUO

---

README.md
docs/gcp/filestore.md

Add blog post around Using Filestore in OSD in GCP for provide ReadWriteMany storage to the apps.

added post to use filestore in osd in gcp

---

README.md
docs/rosa/private-link/public-ingress.md

add public ingress for PL

---

docs/rosa/sts/README.md

* Use simplified --mode auto -y 
* Removed old create roles/oidc - use new auto mode
* Set default example version to latest 4.10.15
* udpated to rosa cli 1.2.2 links

simplify to --mode auto -y and update to 4.10.15 as default ver

---

docs/rosa/federated-metrics-prometheus/README.md

fix bugs in rosa federated metrics doc

---

docs/aro/egress-ipam-operator.md
docs/aro/private-cluster/create-cluster.sh
docs/aro/quickstart-aro/create-cluster.sh

update aro egress ipam instructions

---

docs/aro/federated-metrics/README.md
docs/aro/federated-metrics/user-workload-monitoring-config.yaml
docs/rosa/cluster-metrics-to-aws-prometheus/README.md
docs/rosa/federated-metrics/README.md
docs/rosa/federated-metrics/user-workload-monitoring-config.yaml

fix cluster monitoring remotewrite

---

docs/rosa/aws-secrets-manager-csi/README.md
docs/security/secrets-store-csi/aws-provider-installer.yaml

The ASCP solution is one year old and outdated. This PR fixed the problem and simplify the deployment

update the ASCP solution. simplify the deployment

---

docs/aro/vpn/README.md

Added new instructions to create certificates with easy-rsa

updated with new easyrsa instructions

---

README.md
docs/misc/oadp/rosa-sts/README.md

create oadp on STS instructions

---

README.md
docs/aro/static-ip-load-balancer/README.md

Covers similar content as the AKS guide located here: https://learn.microsoft.com/en-us/azure/aks/static-ip

Adding static IP load balancer how to guide

---

docs/aro/static-ip-load-balancer/README.md

This is why I shouldn't write documentation at midnight...

Fixing mistakes 

---

docs/security/secrets-store-csi/azure-key-vault.md

The helm repo was moved to another URL.

reference to the github helm repo fixed

---

docs/rosa/ecr/README.md

Added ECR Lightboard video

---

docs/quickstart-rosa.md

Added ROSA 101 Lightboard video

Added 101 Lightboard link

---

docs/rosa/sts-with-private-link/README.md

Adding missing delete IGW in Cleanup

Added missing del igw

---

docs/quickstart-rosa.md

Fixed youtube link formatting and update create and delete steps

Update create/delete steps -2

---

docs/aws/waf/README.md

Added Lightboard video

---

docs/rosa/sts/README.md

Added Lightboard STS video

---

docs/aro/aro-machinesets/README.md

[draft] Adding Helm Chart to set up extra MachineSets on ARO clusters

[draft]Added ARO Extra MachineSets

---

docs/aro/additional-ingress-controller/README.md

Make this how-to applicable when adding and ingress controller with a private external ip.

Add an Internally scoped router option

---

README.md
docs/rosa/aws-load-balancer-operator/README.md
docs/rosa/aws-load-balancer-operator/load-balancer-operator-policy.json

Add instructions on how to use AWS load balancer operator with STS.
Remove the link to install aws load balancer controller directly.

aws load balancer operator STS

---

README.md

Added Paul's Extra MachineSets on ARO helm chart

Added Extra MachineSets on ARO

---

docs/idp/azuread/README.md

Fixed Image ref in Register a new application in Azure AD section

Fixed img ref

---

CONTRIBUTING.md

Add in step to preview the site locally before submitting PR when contributing.

Add make preview to contributing

---

content/docs/rosa/kms/_index.md

Based on issue reported at: https://github.com/openshift/openshift-docs/issues/55363
- Added the role: openshift-cluster-csi-drivers-ebs-cloud-credential
- Changed the order of when running rosa create cluster
- Updated the storage class reference to gp3, which is the default now.

 Changes in policy json #1 

---

content/docs/aro/upgrade-disconnected-aro/README.md

of verifying image digest version and upgrade path

Minor updates and notes regarding importance

---

content/docs/rosa/verify-permissions/verify-permissions.sh

Removed cloud_credential_operator, image_registry_installer_cloud_credentials, ingress_operator_cloud_credentials, csi_drivers_ebs_cloud_credentials and cloud_network_config_controller_cloud_credentials policies.

Removed old policies

---

content/docs/rosa/verify-permissions/index.md

Removed cloud_credential_operator, image_registry_installer_cloud_credentials, ingress_operator_cloud_credentials, csi_drivers_ebs_cloud_credentials and cloud_network_config_controller_cloud_credentials policies. Also fixed raw url path to script.

fixed script and path to it

---

content/docs/aro/gpu/_index.md

adding additional skus to the doc based on the list of supported GPUs according to this doc
https://learn.microsoft.com/en-us/azure/openshift/howto-gpu-workloads

adding the additional supported gpu skus

---

content/docs/aro/federated-metrics/index.md

fixed command typo(s) in step 6 and 8

fixed command typo

---

content/docs/misc/secrets-store-csi/azure-key-vault.md
content/docs/misc/secrets-store-csi/install-kubernetes-secret-store-driver.md

1. Formatting
2. Updating chart versions for CSI driver and Azure Key Vault Provider
3. Suppress `tr` warning `Illegal byte sequence` on Mac
4. Update CSI api to GA from alpha

Updates to Azure Key Vault guide

---

content/docs/rosa/sts/_index.md

Bumped the ROSA version to current default and other minor cleanups.

Deploy ROSA in STS mode minor cleanups

---

content/docs/rosa/gpu/_index.md

adding oc login, changing oc apply to oc create on the yaml files to avoid error message, changing watch command to oc wait for nfd instances

Adding note to oc login, changing few commands

---

content/docs/rosa/aws-secrets-manager-csi/_index.md

1. Formatting
2. Scope trust policy to application service account
3. Add step to delete AWS secret in cleanup

Updates to AWS secrets manager CSI guide

---

content/docs/aro/private-cluster.md

apologies, it's the after effects of sleep deprivation + making a PR at 1am local time :/

fixing up the formatting mess I made from prev PR

---

content/docs/idp/azuread-aro-cli/_index.md

I do not see a value in maintaining a CLI version configuration for AD by MOBB.

delete ad cli version

---

content/docs/aro/gpu/_index.md
content/docs/aro/private-cluster.md

Adding a note about an error that will happen if there is no pull secret added on the cluster during the add of the Nvidia channel

Note about clusters without pull secret

---

content/docs/misc/secrets-store-csi/azure-key-vault.md

Updating keyvault name to work with mac (and linux too)

---

content/docs/aro/private-cluster.md

Replacing ipConfigurations[0].privateIpAddress by ipConfigurations[0].privateIPAddress
The old value (privateIpAddress) was returning null.

Fixing the private ip query

---

content/docs/aro/disaster-recovery/_index.md

just a teeny minor fix for this one

escaping double quotes in hugo

---

content/docs/aro/disaster-recovery/_index.md

also fixing links to the private cluster doc

prev fix failed so let's try with backtick this time

---

content/docs/aro/disaster-recovery/_index.md

plus fixing the double quotes escaping with backtick

replacing docker with podman to pull image from acr

---

content/_index.md
content/docs/aro/aro-acr/index.md

- Rendering tested with Hugo Server
- Tested both with Az cli and Terraform
- TF code ready to be used in the https://github.com/rh-mobb/terraform-aro/blob/main/acr.tf
- Added deployment of an example app using private ACR

Adding ACR in private ARO clusters post 

---

content/docs/misc/oadp/rosa-sts/_index.md

* use oadp 1.2.0 vs. 1.0
* correct malformed DPA
* ensure datamover is not enabled
* Add DPA for CSI volumes and non-CSI Volumes
* snapshotlocation is verified for OADP + ROSA STS
* The following roles were added for non-csi volume snapshot ( thanks tiger! )
"ec2:DescribeVolumes",
"ec2:DescribeVolumeAttribute",
"ec2:DescribeVolumesModifications",
"ec2:DescribeVolumeStatus",

correct the OADP sts install docs

---

content/_index.md
content/docs/rosa/sts-rds/_index.md

1. Create VPC for RDS
2. Create RDS postgresql
3. Add IAM permissions
4. Populate DB
5. Deploy sample app

New blogpost: Connect to RDS with IAM and STS from ROSA

---

content/_index.md
content/docs/aro/custom-domain-private-cluster/_index.md

Added Private ARO Clusters with Custom Domains, also managing the Certificates for ARO.

added custom domain private clusters

---

content/docs/aro/add-infra-nodes/index.md

Should be merged after https://github.com/rh-mobb/helm-charts/pull/65

Update docs for updated chart

---

content/docs/redhat/acm/submariner/aro/_index.md

Fixing a small issue on the ARO cluster setup

replacing ROSA by ARO

---

content/aro/add-infra-nodes/index.md

Updates the documentation to watch on target namespace

[Documentation] Minor nit

---

content/rosa/cross-account-access-openid-connect/index.md

Correct post-dated article to properly promote to production

---

package-lock.json
package.json
themes/rhds/assets/css/main.css
themes/rhds/layouts/partials/collaborate.html

1. Updated `@rhds/elements` to latest version `1.3.0`
2. Tweaked some HTML and styles that changes due to the update.
I did a sweep of the RHDS elements used in the site as far as I can tell after the small tweaks included in this PR everything looks good.  Feel free to drop a 2nd set of eyes across the site.

Chore: update RHDS version

---

content/_index.md
content/aro/shipping-logs-and-metrics-to-azure-blob/index.md

will update the helm chart in the afternoon

adding shipping to az blob on main page and removing hardcoded flag version to always fetch the latest

---

content/aro/egress-ipam-operator.md

removing links to OCP doc and including links to MSFT docs instead

---

content/_index.md
content/rosa/ip-addressing-and-subnets/index.md

It was easier to close my old PR and just start over on this. I created this doc awhile ago to try to address some questions around ip address and subnet utliziation that have come up, and give customers are resource to guide them through planning their environment.

Adding ROSA IP/subnetting doc

---

content/rosa/sts-rds/index.md

Fix some permissions issues related to changes on AWS side

Fix some issues with RDS + STS blogpost

---

content/idp/azuread-aro-cli/index.md
content/idp/group-claims/aro/index.md

Correcting Entra ID to use preferred_username instead of the [unreliable email claim](https://learn.microsoft.com/en-us/entra/identity-platform/migrate-off-email-claim-authorization) and cleaning up some other details

Small AAD/Entra ID Fixes

---

content/rosa/ocp-virt/with-fsx.md

Fixed rendering of  with-fsx.md

---

content/rosa/mas/index.md

terraform typo

---

content/rosa/sts/index.md
content/rosa/sts/prereqs.md

Addressing broken prereqs link

---

content/misc/tls-cipher-customization/index.md
netlify.toml

Removing TLS Cipher Customization article and redirecting to OpenShift docs

---

content/aro/blob-storage-csi/index.md

Fixing the status of Blobfuse Proxy component to reflect supportability

Update the Blobfuse Proxy component status

---

content/gcp/secure-web-proxy/index.md

Hidden preview as this will not go on the homepage until the completion of OSD-25970.
Preview: https://deploy-preview-598--rh-cloud-experts.netlify.app/experts/gcp/secure-web-proxy/

Adding Google Secure Web Proxy documentation

---

content/_index.md
content/rosa/ingress-controller/index.md

fixing ingress controller documentation

fix ingress doc

---

content/rhoai/aro-rag/index.md

updating the title

---

content/rosa/entra-external-auth/index.md

Adding instructions for installing the Krew plugin manager / oidc-login plugin
Adding commands to produce kubeconfig files

Fix extauth

---

content/_index.md
content/rosa/local-zones/index.md

Guide to use Local-Zones in ROSA Classic

local-zones for rosa classic

---

content/_index.md
content/rosa/ec2-migration-to-rosa/index.md

- Complete migration guide with Terraform automation for deploying EC2 instances and migrating them to OpenShift Virtualization via S3/EFS export workflow

New article : Migrating EC2 Instances to OpenShift Virtualization
