rh-mobb/documentation

- .github/config/.spellcheck.yml
- .github/workflows/github-actions-spellcheck.yaml
Fix malformatted YAML and update to .16.   Failure word list appears much smaller ignoring code blocks correctly and we may be able to track a smaller group of custom words.
> Fix the yaml for spellchecker and update revision to .16

- _layouts/default.html
Add a warning box for documentation on mobb.ninja - should show up in all content pages (not necessarily in the github repo since github doesn't use jekyll theme in source code)
> Docswarning

- docs/quickstart-rosa.md
add the notes about the missing ELB  role for new vpcs to rosa quick start guide
aws iam create-service-linked-role --aws-service-name \
"elasticloadbalancing.amazonaws.com"
> add tle ELB notes to the simple rosa getting started guide

- Makefile
The preview is breaking, since Jekyll released a new docker image latest. We should use a tag for preview and build in make file. 3.8.6 is the latest 3 version
> use specified version for jekyll container

- docs/rosa/cluster-metrics-to-aws-prometheus/README.md
$PROM_SA-cw iam policy referenced $SCRATCH_DIR/PermissionPolicyIngest.json policy-document which was created and used for $PROM_SA-prom iam policy.
> Fix policy-document reference for cw iam policy

- docs/idp/azuread-aro-cli/README.md
After az cli 2.38 got released, making the application for authentication an enterprise app works now with 
```
az ad sp update --id $APPID --set 'tags=["WindowsAzureActiveDirectoryIntegratedApp"]'
```
Also, for az 2.37, instead of using a container with the older version, `az rest` can be used
```
APP_ID=$(az ad app list --display-name $DISPLAYNAME --query [].id -o tsv)
az rest --method PATCH --url https://graph.microsoft.com/v1.0/applications/$APP_ID --body '{"tags":["WindowsAzureActiveDirectoryIntegratedApp"]}'
```
both is changed with this pr
> Aad cli mod01

- docs/aro/private-cluster.md
(InvalidResourceName) Resource name Allow Egress is invalid. The name can be up to 80 characters long. It must begin with a word character, and it must end with a word character or with '_'. The name may contain word characters or '.', '-', '_'.
Code: InvalidResourceName
Message: Resource name Allow Egress is invalid. The name can be up to 80 characters long. It must begin with a word character, and it must end with a word character or with '_'. The name may contain word characters or '.', '-', '_'.
Fixing this bug in Firewall Rule Collection name for allowing https traffic
> removing the space in the Allow Egress rule collection name

- docs/rosa/clf-cloudwatch-sts/README.md
As-is, the IAM trust policy would allow any request originating from the OIDC provider to do an `sts:AssumeRoleWithWebIdentity` into the role. Added a string match that validates that it comes from the service account the log collector runs as on the cluster.
> Tightening IAM trust policy rules

- docs/aro/gpu/README.md
https://docs.microsoft.com/en-us/azure/openshift/howto-gpu-workloads#request-gpu-quota is wrong as well. 
NCas T4 v3 instance types can be found here: https://docs.microsoft.com/en-us/azure/virtual-machines/nct4-v3-series
> Fix typo on Azure ARO GPU Instance Type

- docs/rosa/sts-with-private-link/README.md
Option 2: Create a **jumphost** instance using the AWS CLI - missing double quotes in command aws ec2 create-security-group
> fixed missing double quotes

- docs/rosa/private-link/public-ingress.md
In a private cluster with PrivateLink, the customdomain endpoint is created in a private Route53 zone of ROSA.
And domain names belonging to private Route53 zones can't be resolved from the internet, but I needed to make the sample application using the CDO accessible from the internet.
The customdomain endpoint is "alias"ed to the external CLB name created by CDO like the below.
*.acme.mycluster.12ab.p1.openshiftapps.com A a9db5fabcd1234-972115757.ap-northeast-1.elb.amazonaws.com.
( customdomain endpoint) ( CLB name )
So, I changed the CNAME target from customdomain endpoint to the CLB domain name so that the sample application can be accessed from the internet.
> change CNAME target from CDO endpoint to CLB name

- content/docs/rosa/ecr-secret-operator/_index.md
The ECR Secret Operator page has two broken links. This PR fixes the links to point to the correct pages.
> Fix broken links

- content/_index.md
- content/docs/rosa/external-dns/_index.md
Note ExternalDNS operator does not support IRSA/STS yet and requires long lived IAM credentials.  See https://github.com/openshift/external-dns-operator/blob/main/api/v1beta1/externaldns_types.go#L260.
> New doc for configuring ExternalDNS operator with ROSA custom domain

- content/_index.md
- content/docs/misc/egress-ip/_index.md
- content/docs/rosa/egress-ip/_index.md
Fixes #289 
The following documentation for a demo is added:
- Egress IP assignment based on namespace
- Egress IP assignment based on pod
- Document current limitations (bugs)
- Show successful connection based on egress IP
- Show unsuccessful connection based on egress IP not in list
> feat: add egress ip documentation

- content/docs/idp/az-ad-grp-sync/_index.md
fixed "Add API Permissions to Azure AD App Registration" section image and ‘ API Permissions entries
> Fixed AZ AD GRP SYNC app reg page links

- content/docs/aro/private-cluster.md
adding sshuttle install command for macos and linux prereqs, getting 'aro create cluster' command out of prev section's indentation, also i might do another PR on this one next week
> adding sshuttle install, fixing aro create indent

- config.toml
Change the hugo configuration for our template to display the copy-to-clipboard button only on fenced or indented code blocks, not inline code that is surrounded by single backticks.
In our docs, we are consistent about using fenced or indented code blocks when we have an example that we intend someone to copy-paste, and we use inline code to denote that something is literal.
> Disable copy button on inline code

- content/docs/idp/azuread-aro/_index.md
- content/docs/idp/azuread/_index.md
Customers using the GroupSync Operator are consistently running into this issue because our docs have changed and are missing configuration required to make the IdP pass tokens that match up with the users created in `Group` resources by the GSO.
Namely, when querying Azure, the IdP config needs to ask for the `email` and `profile` scopes in addition to the default `opened` one, otherwise the fields don't through correctly and the user ends up being represented as their Azure UUID rather than their e-mail, which is what GroupSync assumes.
We should probably re-work our IdP config docs as they're getting pretty scattered and seem to have some inconsistencies in them.
> Adding missing extra-scopes flag to IdP creation

- content/docs/rosa/federated-metrics/_index.md
Small change to correct the spacing of the S3 access policy in the markdown document.
> Fix spacing for ROSA federated metrics AWS prep policy for S3 access

- content/docs/rosa/egress-ip/_index.md
This PR clarifies the following:
- Egress IP selection as related to the VPC range
- Adds recommendation for reserving the IPs via a CIDR reservation
> docs: clarify ip ranges and add cidr reservation

- content/docs/rosa/aws-secrets-manager-csi/_index.md
This references the wrong namespace
> Small fix for AWS CSI Secrets Driver uninstall docs

- content/docs/rosa/clf-cloudwatch-sts/_index.md
original command did not strip out alphanumeric identifier in cluster name
> Yank cluster name correctly in log forwarding guide

- content/docs/aro/static-ip-load-balancer/index.md
- content/docs/aro/user-workload-monitoring/index.md
The documents "Configure A Load Balancer Service To Use A Static Public IP" and "User Workload Monitoring on Azure Red Hat OpenShift" are both about ARO but were incorrectly filed under the ROSA directory.
Move them to their correct locations and add aliases so that any use of the previous URLs still redirects to the new locations.
> Move ARO docs that had been under ROSA

- content/docs/misc/oadp/rosa-sts/_index.md
related-bug: https://issues.redhat.com/browse/OADP-1057 
ensure the dpa supports imagestream backup and restore
> DPA update to add bucket region to support imagestream

- content/docs/idp/group-claims/aro/_index.md
The Microsoft Graph API is documented to respond on the standard HTTPS port, so that is the only port we need to allow through.
Quote the documentation:
> The Microsoft Graph API offers a single endpoint, https://graph.microsoft.com/
Reference: https://learn.microsoft.com/en-us/graph/overview
> docs/idp/group-claims/aro: Restrict firewall rule to port 443

- content/docs/idp/group-claims/rosa/_index.md
Without the `--extra-scopes` parameter, the IdP doesn't return all of the needed claims and it's unable to match Users to the Groups that come through in the claims.
> Adding missing '--extra-scopes' parameter to IdP create command

- content/docs/aro/egress-ipam-operator.md
egressip-ipam-operator doesn't work with OVNKubernetes, so clarify that this whole article only works for clusters still using the old CNI.
> Clarify egressip-ipam needs ARO 4.10 or earlier

- content/docs/aro/private-cluster.md
- content/docs/quickstart-aro.md
1. The dependency on service endpoints was removed back in June (see https://learn.microsoft.com/en-us/azure/openshift/azure-redhat-openshift-release-notes#version-412---august-2023).  This update removes service endpoints in our installation guides.
**Why does this matter**
Some customers have Azure policies that disallow Service Endpoints.  We don't want to give customers the impression that service endpoints are required in installation, if we don't actually use these anymore.
2. Disabling network policies on the private link service is now optional.  This update makes a note that if the customer chooses to skip this step, the ARO RP will automatically disable this for the customer.  Also - the link we provided is incorrect.  We are talking about private link network policies, *not* …
> Remove service endpoints and update PL note

- CONTRIBUTING.md
- content/_index.md
- content/misc/references.md
- content/rosa/private-link/_index.md
- content/rosa/private-link/public-ingress.md
- content/rosa/sts-with-private-link/index.md
- content/rosa/vpn/index.md
- netlify.toml
The term PrivateLink is an AWS product and should be used consistently in our documentation. I have renamed all of the instances of `Private Link` when referenced in ROSA/AWS documentation to `PrivateLink`.
> Rename all ROSA Private Link instances with PrivateLink

- themes/rhds/assets/css/main.css
1. Corrected the rhds token usage for the code-block copy button on a light background.  Fixes accessibility issue in #446
> fix: color contrast of code copy button

- content/aro/odf/index.md
The location where the example is displayed could lead the reader to the idea that the resource should already be available, while it is not. Only will be available after the step to create the storage cluster. So I'm moving this part to the end, after the creation of the storage cluster and the validation.
> Moving example of what ODF looks like to the end

- themes/rhds/layouts/partials/eddl/page-load-started.html
Issue:
- Page Load Started is not tracking view size for analytics.
Change:
- Enhancement to Page Load Started event allows us to get a rough idea of the browser window size.
See `siteExperience` in [EDDL Spec](https://github.com/searchdiscovery/redhat-datalayer/blob/main/EDDL/global-datalayer.md#variable-definitions-13)
> Adds site experience to Page Load Started.

- content/misc/secrets-store-csi/hashicorp-vault.md
- content/misc/secrets-store-csi/install-kubernetes-secret-store-driver.md
- content/rosa/aws-secrets-manager-csi/index.md
Changes:
- Add label `security.openshift.io/csi-ephemeral-volume-profile: restricted` on CSI Driver API object for 4.13
- Update Vault instructions to consistently use `oc`. (currently mixes `kubectl` and `oc`)
- Clarify Vault instructions to check the Service Account Issuer in another terminal, outside the vault session
Tested this on ARO v4.12 and ROSA v4.13.  Adding the label does not break previous versions.
> Add pod security label on CSI driver for 4.13

- content/aro/blob-storage-csi/index.md
This guide has been working well with ARO 4.11, but it is not with 4.12. This fix is already tested in version 4.11 and 4.12, and it works like a charm.
> fix: for aro version 4.12

- content/o11y/ocp-grafana/index.md
The link of mobb helm repo has been out-dated,
```
$ helm repo add mobb https://mobb.github.io/helm-charts
Error: looks like "https://mobb.github.io/helm-charts" is not a valid chart repository or cannot be reached: failed to fetch https://mobb.github.io/helm-charts/index.yaml : 404 Not Found
```
this works 
```
$ helm repo add mobb https://rh-mobb.github.io/helm-charts/                                                                                                                                                                                  
"mobb" has been added to your repositories
```
> Update the MOBB helm repo link

- content/rosa/ingress-controller/index.md
This is a simple update that removes the duplicate definition of the `SCRATCH_DIR` environment variable.
> Remove extra environment variable definition

- content/aro/private-cluster.md
Made some minor changes around user defined networks.
Note based on the fact you all said:
`If you want to change the default behavior to restrict the Internet Egress, you have to set --outbound-type during the creation of the cluster to UserDefinedRouting`
That my alert below is true, but I have not actually run the create command so correct me if I am wrong
```
{{% alert state="info" %}} Be sure to add the `--outbound-type UserDefinedRouting` flag if you are not using the default routing.{{% /alert %}}
```
> Minor clarity changes around UserDefinedNetworks

- content/aro/azure-arc-integration/index.md
For Key Vault, Add the missing steps to create a service principal, capture its creds, and set a policy so that the service principal can get secrets from the vault. Add a command so that people know how to find their tenant ID.
When enabling observability, fix a bug where the token was getting a backslash-n applied to it.
Fix grep command to find named pods.
Remove `--infrastructure="auto"` since this is no longer supported.
> Fix bugs in Arc instructions

- content/aro/acm-odf-aro/index.md
The addon config has nothing to do with Submariner and is instead needed to enable ACM agent capabilities on the cluster.
Fix its description so that if someone is following these instructions without the intent to use Submariner, theyu still follow this step.
> Fix description of addon config step

- content/aro/frontdoor/index.md
Fix bug where the Front Door validation token got wrapped in a set of quotation marks, causing domain validation to fail. When using az with --query for a single field, that field still has JSON representation by default, and in this case, that means it is quoted because it is a string. If the TXT record contains a value that has an extra pair of quotes, domain validation will never move on from the Pending state.
Switching to a tsv representation causes az to return the value without quotes.
> Fix quoting on Front Door validation token

- content/rosa/vpn/index.md
I've tested the VPN configuration and this step is not needed.
From my conversation with @kmcolli , it seems this step was copied from the ARO document.
> Delete unnecessary step

- content/rosa/ingress-controller/index.md
Name of secret for cert_name isn't clear and led to confusion with customer deploy. Recommending a formatting update to clarify.
> Update ROSA Ingress Controller Docs

- content/aro/shipping-logs-and-metrics-to-azure-blob/index.md
With the release versions removed from the [previous docs commit](https://github.com/rh-mobb/documentation/commit/9d905589a81b59eaba2993e741b8893f3f222f80#diff-399fb8f81b390ee72992f1e682c723e23405eebe6bd4ae6088c3dbbc4d1f3574), the patch operator needs to be installed to process the aro-thanos-af helm chart. Otherwise, it will throw the error below.
```
ensure CRDs are installed first, resource mapping not found for name: "cluster-monitoring-config-patcher" namespace: "patch-operator" from "": no matches for kind "Patch" in version "redhatcop.redhat.io/v1alpha1"
ensure CRDs are installed first, resource mapping not found for name: "user-workload-monitoring-config-patcher" namespace: "patch-operator" from "": no matches for kind "Patch" in version "redhatcop.redhat.io/v1alpha1"
ensure CRDs …
```
> Adding steps for patch operator install

- content/aro/azure-arc-integration/index.md
This section is incorrect in several ways:
- It talks about log aggregation but attempts to install the metrics extension
- The extension azuremonitor-metrics currently requires a workaround to use on OpenShift versions 4.13 and above https://access.redhat.com/solutions/7064794
- The extension azuremonitor-metrics is currently not supported by Microsoft on OpenShift per https://learn.microsoft.com/en-us/azure/azure-monitor/containers/kubernetes-monitoring-enable
We can eventually rewrite these to properly instruct on azuremonitor-containers, which is actually how log aggregation works, but for now it's better to prevent anyone from being misled by incorrect instructions.
This gets us part way to #526
> Remove "Enable log aggregation" for now

- content/redhat/gitops/index.md
Can be added back when content is available
> Update gitops page to avoid publishing todo item

- content/aro/registry/index.md
The validation step was missing a variable substitution, and this aligns the instructions with the official MSFT and OCP docs.
> Updating ARO internal registry instructions

- content/rosa/metrics-to-cloudwatch-agent/index.md
Supersedes #515 
Addresses differences in GNU and BSD `sed -i` commands. 
Thanks @yuhkih for the fixes.
> Adding changes from #515 to updated doc

- content/aro/azure-arc-integration/index.md
Make it clearer that Container Insights is the Azure-supported mechanism to ship logs to Azure. Link directly to the Microsoft docs for Container Insights and add some color around how to follow them.
Reword "Observability" into something clearer about the intent of that section, which is about viewing resources and not logs/metrics/traces.
Fixes #526 .
> Clarify Arc Container Insights docs

- content/aro/federated-metrics/index.md
The index.md has some misleading typos where Azure files is mentioned in place of Azure Blob storage which is actually used by the helm charts.
> Fixing typos in index.md  using Azure Blob Storage instead of Azure files.

- content/aro/federated-metrics/index.md
The retention rules aren't applicable for the remote write storage, further configuration on Thanos end is needed to control the retention of metrics in the Azure Blob side.
> Reverting back the note around the retention

- package-lock.json
- package.json
- rollup.config.js
Updated packages to fix dependabot alert https://github.com/rh-mobb/documentation/security/dependabot/6. Also updated additional packages to the latest available and removed deprecated rollup-plugin-terser in favor of @rollup/plugin-terser.
> fix: update npm packages

- content/gcp/cloud-ngfw/index.md
- Changing to allowing egress to all RFC 1918 addresses
- Correction "Private Google Access" language
- Adds missing `inputs3.osdsecuritylogs.splunkcloud.com` endpoint
> Small Cloud NGFW Improvements

- themes/rhds/assets/css/main.css
- themes/rhds/assets/js/main.js
- themes/rhds/layouts/partials/head/importmap.html
- fix order of keyboard nav for codeblocks, on tab: code first -> copy button
- corrected production cdn url for es-shims
> fix: keyboard nav order of codeblocks

- content/rosa/cluster-metrics-to-aws-prometheus/index.md
Lots has changed in both the operators, openshift, and aws.   This uses the newer helm charts that overcomes the issues created by these changes... you know until they change again, such is life.
> update aws prometheus doc

- content/idp/az-ad-grp-sync/index.md
The group and prune parameters are missing an indentation, since as explained on the GroupSync resource, the groups and prune parameters are fields for the azure setting.
```
$ oc explain groupsyncs.spec.providers.azure 
GROUP:      redhatcop.redhat.io
KIND:       GroupSync
VERSION:    v1alpha1
FIELD: azure <Object>
DESCRIPTION:
Azure represents the Azure provider
FIELDS:
...
groups        <[]string>
Groups represents a filtered list of groups to synchronize
...
prune <boolean>
Prune Whether to prune groups that are no longer in Azure. Default is false
```
Meaning that these values should be at the same indentation level as credentialsSecret, and in the MOBB document, they appear at the same indentation level as azure, this causes an Admission Webhook Warning
```
Admission Webhook Warning …
```
> group and prune parameters are missing an indentation

- content/rosa/vpn/index.md
Extra spaces in the import certificate commands have been removed, it causes an issue with the CLI command.
> Removed extra spaces in commands

- content/aro/cert-manager/index.md
The cert-manager guide had a couple of inconsistencies and bugs:
- Namespaces didn't match install via OperatorHub on console
- Bad shell variable escaping on one of the cert install `Job` resources
I also made the use of the `Job` for installing each cert optional and just provided the commands directly with a note to use the `Job` if relying on automation.
> Updated cert-manager docs
